# Generated by Django 6.0.1 on 2026-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_appointment_reminder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('info', 'Informação'), ('warning', 'Alerta'), ('critical', 'Crítico')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('deleted', 'Excluído')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='info_type',
            field=models.CharField(choices=[('allergy', 'Alergia'), ('medication', 'Medicamento'), ('surgery', 'Cirurgia'), ('diagnosis', 'Diagnóstico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('access', 'Solicitação de acesso'), ('security', 'Segurança'), ('cycle', 'Ciclo'), ('appointment', 'Consulta'), ('exam', 'Exame'), ('admin', 'Administrativa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Usuária'), ('clinic', 'Clínica'), ('admin', 'Administrador')], default='patient', max_length=20),
        ),
    ]
