# Generated by Django 6.0.1 on 2026-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_alter_appointment_status_alter_auditlog_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('deleted', 'Removido')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('access', 'Pedido de acesso'), ('security', 'Segurança da conta'), ('cycle', 'Ciclo menstrual'), ('appointment', 'Consulta'), ('exam', 'Exame'), ('admin', 'Aviso importante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Paciente'), ('clinic', 'Clínica'), ('admin', 'Administrador')], default='patient', max_length=20),
        ),
    ]
