# Generated by Django 6.0.1 on 2026-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0005_alter_auditlog_level_alter_exam_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_name',
            field=models.CharField(default='CESMAC', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Paciente'), ('clinic', 'Profissional CESMAC'), ('admin', 'Administrador')], default='patient', max_length=20),
        ),
    ]
