# Generated by Django 6.0.1 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_core", "0006_user_institution_name_user_specialty_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="hidden_by_patient_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
